
# This action builds source-reminder docker image and pushes to Amazon ECR.
name: deploy-source-reminder
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Sets up the Action's environment with AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Logs into ECR using the environment's configured AWS credentials
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build the docker image, tag it with the git commit, and push to AWS ECR
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: source-reminder
          IMAGE_TAG: ${{ github.sha }}
        working-directory: source-reminder
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG